name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Trigger workflow on push to the main branch (adjust to your branch name)

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    # Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v2

    # Set up Docker Buildx for multi-platform support
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Log into Docker Hub using GitHub secrets
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Docker Hub username stored in GitHub Secrets
        password: ${{ secrets.DOCKER_PASSWORD }}  # Docker Hub password stored in GitHub Secrets

    # Build the Docker image
    - name: Build Docker image
      run: |
        cd home-inventory-python-api
        docker build --build-arg DATABASE_URL=${{ secrets.DATABASE_URL }} --build-arg EMAIL_ADDRESS=${{ secrets.EMAIL_ADDRESS }} --build-arg EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }} -f ./Dockerfile -t crazydatabaseuser/home-inventory-api .
        docker build --build-arg DATABASE_URL=${{ secrets.DATABASE_URL }} --build-arg EMAIL_ADDRESS=${{ secrets.EMAIL_ADDRESS }} --build-arg EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }} -f ./Dockerfile -t crazydatabaseuser/home-inventory-api:v1 .

    # Push the Docker image to Docker Hub (using github secrets)
    - name: Push Docker image
      run: |
        docker push crazydatabaseuser/home-inventory-api
        docker push crazydatabaseuser/home-inventory-api:v1
